# Generated by Django 5.1.3 on 2024-11-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(default='', max_length=255),
        ),
    ]
